# -*- coding: utf-8 -*-
"""Shallow_neural_network_for_imageClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naKiAhdJw82-JJvbZy9vrQN6V0Uei9Sb
"""

!pip install tensorflow

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy
import os
import PIL
import math
from tensorflow import keras


IMG_WIDTH = 224
IMG_HEIGHT = 224
IMG_CHANNELS = 3
EPOCHS = 10

CLASS_NAMES = ['roses' , 'tulips' , 'daisy' , 'dandelion' , 'sunflowers']

def read_and_decode(filename, reshape_dims):

  img_bytes = tf.io.read_file(filename)

  # convert the jpeg images into RGB format
  img = tf.image.decode_jpeg(img_bytes, channels=3)

  # convert the pixel intensity in range [0,1]
  img = tf.image.convert_image_dtype(img, tf.float32)

  # convert image to match the desired demension
  img = tf.image.resize(img, reshape_dims)

  return img

def parse_csv_line(csv_line):
  # record_defaults specify the data types for each column
  record_default = ["" , ""]
  filename, label_string = tf.io.decode_csv(csv_line, record_default)
  img = read_and_decode(filename=filename, reshape_dims=[IMG_WIDTH, IMG_HEIGHT])
  label = tf.argmax(tf.math.equal(CLASS_NAMES , label_string))

  return img, label

# define and prepare dataset
train_dataset = (
    tf.data.TextLineDataset("gs://cloud-ml-data/img/flower_photos/train_set.csv")
    .map(parse_csv_line, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(16)
    .prefetch(tf.data.experimental.AUTOTUNE)
)

eval_dataset = (
    tf.data.TextLineDataset("gs://cloud-ml-data/img/flower_photos/train_set.csv")
    .map(parse_csv_line, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(16)
    .prefetch(tf.data.experimental.AUTOTUNE)
)

for image_batch, label_batch in train_dataset.take(3):
  print("Image Batch Shape" , image_batch.shape)
  print("Label Batch Shape" , label_batch.shape)
  print("Label" , label_batch.numpy())

for image_batch, label_batch in train_dataset.take(3):
  first_image = image_batch[0]
  first_label = label_batch[0]

  plt.imshow(first_image.numpy())
  plt.title(f"Label: {CLASS_NAMES[first_label]}")
  plt.axis('off')
  plt.show()

for image_batch, label_batch in train_dataset.take(1):
  fig, axes = plt.subplots(4, 4, figsize = (10,10))

  for i in range(16):
    ax = axes[i // 4, i % 4]
    ax.imshow(image_batch[i].numpy())
    ax.axis('off')
    ax.set_title(CLASS_NAMES[label_batch[i]])

  plt.tight_layout()
  plt.show()

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS)),
    keras.layers.Dense(len(CLASS_NAMES), activation='softmax')
])

model.compile(
    optimizer='adam',
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=["accuracy"]
)

history = model.fit(
    train_dataset,
    validation_data=eval_dataset,
    epochs = EPOCHS
)

plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()

plt.plot(history.history["accuracy"] , label="Training Accuracy")
plt.plot(history.history["val_accuracy"] , label="Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

"""#Inference"""

for image_batch, label_batch in eval_dataset.take(1):
  batch_predictions = model.predict(image_batch)
  predictions = numpy.argmax(batch_predictions, axis=1)

    # 2. Setup grid dimensions
  num_images = image_batch.shape[0]
  num_cols = 4
    # Calculate rows needed (e.g., 16 images / 4 cols = 4 rows)
  num_rows = math.ceil(num_images / num_cols)
  fig, axes = plt.subplots(num_rows, num_cols, figsize=(12, 12))
  axes = axes.flatten()

  for i in range(num_images):
    ax = axes[i]
    ax.imshow(image_batch[i].numpy())
    ax.axis('off')

    predicted_classes = CLASS_NAMES[predictions[i]]
    actual_classes = CLASS_NAMES[label_batch[i]]
    color = 'green' if predicted_classes == actual_classes else 'red'

    ax.set_title(f"Predicted: {predicted_classes}\nActual: {actual_classes}" , color=color)

  plt.tight_layout()
  plt.show()

